name: Update jcinema.m3u

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */06 * * *'

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Ensure playlist directory exists
      run: mkdir -p playlist

    - name: Fetch file from hosting
      run: |
        curl -o playlist/jcinema.m3u https://raw.githubusercontent.com/alex8875/m3u/main/jcinema.m3u

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add playlist/jcinema.m3u
        git commit -m "Update jcinema.m3u file"
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
        git push origin HEAD:main
